apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    purpose: debug
spec:
  containers:
  - name: debug
    image: mathslogic/debug:4.0.0