apiVersion: v1
kind: Secret
metadata:
  namespace: roboshop
  name: rabbitmq-secret
type: Opaque
data:
  # Values must be base64 encoded string outputs (e.g., echo -n "admin" | base64)
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
       project: roboshop
       tier: db
       component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: mathslogic/rabbitmq:4.0.0
        envFrom:
        - secretRef:
            name: rabbitmq-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672