apiVersion: v1
kind: Secret
metadata:
  namespace: roboshop
  name: mysql-secret
type: Opaque
data:
  # Values must be base64 encoded string outputs (e.g., echo -n "admin" | base64)
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
       project: roboshop
       tier: db
       component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mathslogic/mysql:4.0.0
        envFrom:
        - secretRef:
            name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306